// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy4jpr_9HYKIHp6byeXGsPhN2bP4PjOQQ',
    appId: '1:927592659019:web:3a796d7ac0268e1dbfb5ce',
    messagingSenderId: '927592659019',
    projectId: 'chopnow-vendor',
    authDomain: 'chopnow-vendor.firebaseapp.com',
    storageBucket: 'chopnow-vendor.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOlg2ZHCKE5w1TQ7qBwrG7kF8zjjKcMZE',
    appId: '1:927592659019:android:822d7cf0cda67f5fbfb5ce',
    messagingSenderId: '927592659019',
    projectId: 'chopnow-vendor',
    storageBucket: 'chopnow-vendor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkXerMB_r7Q3T-kysf6MMilCLoVn4NnCQ',
    appId: '1:927592659019:ios:fa2f67cbd7807fd7bfb5ce',
    messagingSenderId: '927592659019',
    projectId: 'chopnow-vendor',
    storageBucket: 'chopnow-vendor.firebasestorage.app',
    iosBundleId: 'com.example.vendor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkXerMB_r7Q3T-kysf6MMilCLoVn4NnCQ',
    appId: '1:927592659019:ios:fa2f67cbd7807fd7bfb5ce',
    messagingSenderId: '927592659019',
    projectId: 'chopnow-vendor',
    storageBucket: 'chopnow-vendor.firebasestorage.app',
    iosBundleId: 'com.example.vendor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy4jpr_9HYKIHp6byeXGsPhN2bP4PjOQQ',
    appId: '1:927592659019:web:c801b707f34b22f4bfb5ce',
    messagingSenderId: '927592659019',
    projectId: 'chopnow-vendor',
    authDomain: 'chopnow-vendor.firebaseapp.com',
    storageBucket: 'chopnow-vendor.firebasestorage.app',
  );

}